
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from './components/SideBar'
import Bar from './searchtable'
import Layout from './components/Layout'
import { Router } from 'react-router-dom'

import { ApolloWrapper } from './lib/apollo-wrapper'
import { ApolloClient, ApolloProvider, InMemoryCache } from '@apollo/client'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


const client =new ApolloClient({
  cache: new InMemoryCache(),
  uri: 'https://closing-muskrat-16.hasura.app/v1/graphql',
  headers: {
    'content-type' : 'application/json',
    'x-hasura-admin-secret': 'GEBiWvxHO1XpFOhC17rJzg3KfLM05h73cy216qkOlraHyrFmSMi0Wds22mNuWTVO'
  }
  
});



export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    
    <html lang="en">

      <html lang="en">
        <body className={`${inter.className}    bg-slate-200` }>
         
          <ApolloWrapper>{children}</ApolloWrapper>
          
        </body>
      </html>
      
    </html>

  )
}

/*
<body className={`${inter.className}  bg-orange-600`  }>

      {children}
      
      </body>




      <html lang="en">

      <html lang="en">
        <body className={`${inter.className}  bg-orange-600` }>
          <ApolloProvider client={client}>
                      <ApolloWrapper>{children}</ApolloWrapper>
          </ApolloProvider>

        </body>
      </html>
      
    </html>


      */